<?xml version="1.0" encoding="utf-8"?><!DOCTYPE lyra [
  <!ELEMENT lyra (Songs,Translations)>
  <!ELEMENT Songs (Song*) >
  <!ELEMENT Song (Number,Title,Text) >
  <!ELEMENT Translations (Translation*)>
  <!ELEMENT Translation (Title,Text)>
  <!ELEMENT Number (#PCDATA)>
  <!ELEMENT Title (#PCDATA)>
  <!ELEMENT Text (#PCDATA)>
  <!ATTLIST lyra ver CDATA #REQUIRED>
  <!ATTLIST lyra date CDATA #REQUIRED>
  <!ATTLIST Song id ID #REQUIRED>
  <!ATTLIST Song trans IDREFS #REQUIRED>
  <!ATTLIST Song zus CDATA #REQUIRED>
  <!ATTLIST Translation id ID #REQUIRED>
  <!ATTLIST Translation lang CDATA #REQUIRED>
  <!ATTLIST Translation unform CDATA #REQUIRED>]><lyra ver="1.7-3" date="2005/04/02" stylesref="lyrastyles.xml"><Songs><Song id="s0001" trans="t0001" zus="tes" style=""><Number>1</Number><Title>Jubilate Deo</Title><Text>Jubilate Deo, jubilate Deo. Alleluja!
</Text></Song><Song id="s7001" trans="" zus="" style="1b1ffd51-9e2f-4536-a383-55297a1aff6e"><Number>2</Number><Title>Laudato si</Title><Text>&lt;refrain&gt;Laudato si, o mi Signore   (4x)&lt;/refrain&gt;

Sei gepriesen für alle deine Werke
Sei gepriesen für Sonne, Mond und Sterne
Sei gepriesen für Meer und Kontinente
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen für Licht und Dunkelheiten
    Sei gepriesen für Nächte und für Tage
    Sei gepriesen für Jahre und Sekunden
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen für Wolken, Wind und Regen
Sei gepriesen, du lässt die Quellen springen
Sei gepriesen, du lässt die Felder reifen
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen für deine hohen Berge
    Sei gepriesen für Feld und Wald und Täler
    Sei gepriesen für deiner Bäume Schatten
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, du lässt die Vögel kreisen
Sei gepriesen, wenn sie am Morgen singen
Sei gepriesen für alle deine Tiere
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen, denn du, Herr, schufst die Menschen
    Sei gepriesen, er ist ein Bild der Liebe
    Sei gepriesen für jedes Volk der Erde
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, du selbst bist Mensch geworden
Sei gepriesen für Jesus, unsern Bruder
Sei gepriesen, wir tragen seinen Namen
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen, er hat zu uns gesprochen
    Sei gepriesen, er ist für uns gestorben
    Sei gepriesen, er ist vom Tod erstanden
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, Herr über Tod und Leben
Sei gepriesen, du öffnest uns die Zukunft
Sei gepriesen, in Ewigkeit gepriesen
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen, denn du, Herr, schufst die Menschen
    Sei gepriesen, er ist ein Bild der Liebe
    Sei gepriesen für jedes Volk der Erde
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, du selbst bist Mensch geworden
Sei gepriesen für Jesus, unsern Bruder
Sei gepriesen, wir tragen seinen Namen
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen, er hat zu uns gesprochen
    Sei gepriesen, er ist für uns gestorben
    Sei gepriesen, er ist vom Tod erstanden
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, Herr über Tod und Leben
Sei gepriesen, du öffnest uns die Zukunft
Sei gepriesen, in Ewigkeit gepriesen
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen, denn du, Herr, schufst die Menschen
    Sei gepriesen, er ist ein Bild der Liebe
    Sei gepriesen für jedes Volk der Erde
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, du selbst bist Mensch geworden
Sei gepriesen für Jesus, unsern Bruder
Sei gepriesen, wir tragen seinen Namen
Sei gepriesen, denn du bist wunderbar, Herr

    Sei gepriesen, er hat zu uns gesprochen
    Sei gepriesen, er ist für uns gestorben
    Sei gepriesen, er ist vom Tod erstanden
    Sei gepriesen, denn du bist wunderbar, Herr

Sei gepriesen, Herr über Tod und Leben
Sei gepriesen, du öffnest uns die Zukunft
Sei gepriesen, in Ewigkeit gepriesen
Sei gepriesen, denn du bist wunderbar, Herr








</Text></Song></Songs><Translations><Translation lang="dt" id="t0001" unform="no"><Title>Jubelt Gott zu</Title><Text>(Jubelt Gott zu, Halleluja!)</Text></Translation></Translations></lyra>