<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE lyralists[
  <!ELEMENT lists (List)>
  <!ELEMENT List (Title,Author,Date,Songs) >
  <!ELEMENT Title (CDATA) >
  <!ELEMENT Author (CDATA) >
  <!ELEMENT Date (CDATA) >
  <!ELEMENT Songs (CDATA) >]>
<lists>
  <List>
    <Title>Standardliste</Title>
    <Author>lyra</Author>
    <Date>2004/10/25</Date>
    <Songs>s0001</Songs>
  </List>
</lists>